name: Isaac Timothy
favicon: null
layout_spectrum: 0.6158257862553
typography_spectrum: 0.40484330570325255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.27114785253070295
  lightness: 0.6469984371215105
  saturation: 0.2666998114436865
  rhythmicContrast: 0.6548762128222734
purpose: []
